# Generated by Django 3.2.6 on 2021-09-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
